USE [master]
GO
/****** Object:  Database [ENCHERES_BDD]    Script Date: 02/12/2020 14:14:28 ******/
CREATE DATABASE [ENCHERES_BDD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ENCHERES_BDD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ENCHERES_BDD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ENCHERES_BDD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ENCHERES_BDD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ENCHERES_BDD] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ENCHERES_BDD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ENCHERES_BDD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ENCHERES_BDD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ENCHERES_BDD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ENCHERES_BDD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ENCHERES_BDD] SET ARITHABORT OFF 
GO
ALTER DATABASE [ENCHERES_BDD] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ENCHERES_BDD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ENCHERES_BDD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ENCHERES_BDD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ENCHERES_BDD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ENCHERES_BDD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ENCHERES_BDD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ENCHERES_BDD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ENCHERES_BDD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ENCHERES_BDD] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ENCHERES_BDD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ENCHERES_BDD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ENCHERES_BDD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ENCHERES_BDD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ENCHERES_BDD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ENCHERES_BDD] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ENCHERES_BDD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ENCHERES_BDD] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ENCHERES_BDD] SET  MULTI_USER 
GO
ALTER DATABASE [ENCHERES_BDD] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ENCHERES_BDD] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ENCHERES_BDD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ENCHERES_BDD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ENCHERES_BDD] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ENCHERES_BDD] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ENCHERES_BDD] SET QUERY_STORE = OFF
GO
USE [ENCHERES_BDD]
GO
/****** Object:  Table [dbo].[ARTICLES_VENDUS]    Script Date: 02/12/2020 14:14:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ARTICLES_VENDUS](
	[no_article] [int] IDENTITY(1,1) NOT NULL,
	[nom_article] [varchar](30) NOT NULL,
	[description] [varchar](300) NOT NULL,
	[date_debut_enchere] [datetime] NOT NULL,
	[date_fin_enchere] [datetime] NOT NULL,
	[prix_initial] [int] NULL,
	[prix_vente] [int] NULL,
	[no_utilisateur] [int] NOT NULL,
	[no_categorie] [int] NOT NULL,
	[etat_vente] [char](2) NOT NULL,
	[image] [varchar](150) NULL,
 CONSTRAINT [articles_vendus_pk] PRIMARY KEY CLUSTERED 
(
	[no_article] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CATEGORIES]    Script Date: 02/12/2020 14:14:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CATEGORIES](
	[no_categorie] [int] IDENTITY(1,1) NOT NULL,
	[libelle] [varchar](30) NOT NULL,
 CONSTRAINT [categories_pk] PRIMARY KEY CLUSTERED 
(
	[no_categorie] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ENCHERES]    Script Date: 02/12/2020 14:14:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ENCHERES](
	[no_utilisateur] [int] NOT NULL,
	[no_article] [int] NOT NULL,
	[date_enchere] [datetime] NOT NULL,
	[montant_enchere] [int] NOT NULL,
 CONSTRAINT [encheres_pk] PRIMARY KEY CLUSTERED 
(
	[no_utilisateur] ASC,
	[no_article] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RETRAITS]    Script Date: 02/12/2020 14:14:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RETRAITS](
	[no_article] [int] NOT NULL,
	[rue] [varchar](30) NOT NULL,
	[code_postal] [varchar](15) NOT NULL,
	[ville] [varchar](30) NOT NULL,
 CONSTRAINT [retraits_pk] PRIMARY KEY CLUSTERED 
(
	[no_article] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UTILISATEURS]    Script Date: 02/12/2020 14:14:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UTILISATEURS](
	[no_utilisateur] [int] IDENTITY(1,1) NOT NULL,
	[pseudo] [varchar](30) NOT NULL,
	[nom] [varchar](30) NOT NULL,
	[prenom] [varchar](30) NOT NULL,
	[email] [varchar](50) NOT NULL,
	[telephone] [varchar](15) NULL,
	[rue] [varchar](30) NOT NULL,
	[code_postal] [varchar](10) NOT NULL,
	[ville] [varchar](30) NOT NULL,
	[mot_de_passe] [varchar](30) NOT NULL,
	[credit] [int] NOT NULL,
	[administrateur] [bit] NOT NULL,
 CONSTRAINT [utilisateurs_pk] PRIMARY KEY CLUSTERED 
(
	[no_utilisateur] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [utilisateurs_email_uq] UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [utilisateurs_pseudo_uq] UNIQUE NONCLUSTERED 
(
	[pseudo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ARTICLES_VENDUS] ADD  DEFAULT ('CR') FOR [etat_vente]
GO
ALTER TABLE [dbo].[ARTICLES_VENDUS]  WITH CHECK ADD  CONSTRAINT [articles_utilisateurs_fk] FOREIGN KEY([no_utilisateur])
REFERENCES [dbo].[UTILISATEURS] ([no_utilisateur])
GO
ALTER TABLE [dbo].[ARTICLES_VENDUS] CHECK CONSTRAINT [articles_utilisateurs_fk]
GO
ALTER TABLE [dbo].[ARTICLES_VENDUS]  WITH CHECK ADD  CONSTRAINT [articles_vendus_categories_fk] FOREIGN KEY([no_categorie])
REFERENCES [dbo].[CATEGORIES] ([no_categorie])
GO
ALTER TABLE [dbo].[ARTICLES_VENDUS] CHECK CONSTRAINT [articles_vendus_categories_fk]
GO
ALTER TABLE [dbo].[ENCHERES]  WITH CHECK ADD  CONSTRAINT [encheres_articles_vendus_fk] FOREIGN KEY([no_article])
REFERENCES [dbo].[ARTICLES_VENDUS] ([no_article])
GO
ALTER TABLE [dbo].[ENCHERES] CHECK CONSTRAINT [encheres_articles_vendus_fk]
GO
ALTER TABLE [dbo].[ENCHERES]  WITH CHECK ADD  CONSTRAINT [ventes_utilisateurs_fk] FOREIGN KEY([no_utilisateur])
REFERENCES [dbo].[UTILISATEURS] ([no_utilisateur])
GO
ALTER TABLE [dbo].[ENCHERES] CHECK CONSTRAINT [ventes_utilisateurs_fk]
GO
ALTER TABLE [dbo].[RETRAITS]  WITH CHECK ADD  CONSTRAINT [retraits_articles_vendus_fk] FOREIGN KEY([no_article])
REFERENCES [dbo].[ARTICLES_VENDUS] ([no_article])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[RETRAITS] CHECK CONSTRAINT [retraits_articles_vendus_fk]
GO
ALTER TABLE [dbo].[ARTICLES_VENDUS]  WITH CHECK ADD  CONSTRAINT [articles_vendus_etat_vente_ck] CHECK  (([etat_vente]='RT' OR [etat_vente]='VD' OR [etat_vente]='EC' OR [etat_vente]='CR'))
GO
ALTER TABLE [dbo].[ARTICLES_VENDUS] CHECK CONSTRAINT [articles_vendus_etat_vente_ck]
GO
/****** Object:  StoredProcedure [dbo].[updateArticle]    Script Date: 02/12/2020 14:14:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[updateArticle]      
AS   
	DECLARE @id int
	DECLARE @montant int
	DECLARE @util int

	--ouvre cursor
	DECLARE db_cursor CURSOR FOR 
	SELECT no_article 
	FROM ARTICLES_VENDUS
	WHERE etat_vente = 'CR' AND GETDATE() >= date_debut_enchere;
	
	OPEN db_cursor  
	FETCH NEXT FROM db_cursor INTO @id 

	WHILE @@FETCH_STATUS = 0  
	BEGIN  
		UPDATE ARTICLES_VENDUS SET  
		etat_vente = 'EC'
		WHERE no_article = @id;   

		FETCH NEXT FROM db_cursor INTO @id 
	END 
	
	--close cursor
	CLOSE db_cursor 
	DEALLOCATE db_cursor;
	
	--ouvre cursor Update article EC
	DECLARE db2_cursor CURSOR FOR 
	SELECT no_article, no_utilisateur
	FROM ARTICLES_VENDUS
	WHERE etat_vente = 'EC' AND GETDATE() > date_fin_enchere;
	
	OPEN db2_cursor  
	FETCH NEXT FROM db2_cursor INTO @id , @util

	WHILE @@FETCH_STATUS = 0  
	BEGIN 
		--set montant vente a zero
		SET @montant = 0;
		DECLARE db3_cursor CURSOR FOR 
		SELECT TOP(1) montant_enchere
		FROM ENCHERES
		WHERE no_article = @id ORDER BY montant_enchere DESC;
		
		OPEN db3_cursor  
		FETCH NEXT FROM db3_cursor INTO @montant 
		
		CLOSE db3_cursor 
		DEALLOCATE db3_cursor;
	
		UPDATE ARTICLES_VENDUS SET  
		etat_vente = 'VD',
		prix_vente = @montant
		WHERE no_article = @id;  

		--Si prix de vente > 0 créditer le propriétaire de l'article
		if @montant > 0 
		BEGIN
			UPDATE UTILISATEURS SET credit += @montant WHERE no_utilisateur = @util;
		END


		FETCH NEXT FROM db2_cursor INTO @id  , @util
	END 
	
	--close cursor
	CLOSE db2_cursor 
	DEALLOCATE db2_cursor;
	
    
GO
USE [master]
GO
ALTER DATABASE [ENCHERES_BDD] SET  READ_WRITE 
GO
